package gui;

import datos.Canal;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Agenda;
/**
 *
 * @author Carlos Z
 */
public class Ventana extends javax.swing.JFrame {

    private Agenda miCanal;
    private Canal canalSeleccionado;

    public Ventana() {
        
        miCanal = new Agenda();

        initComponents();
        cargarDatos();
        interactionButtonParrilla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btParrilla = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        btnBorrar1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setText("Canales");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 30, 210, 40);

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 110, 122, 30);

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel3.setText("Numero:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 160, 122, 30);

        txtNombre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(txtNombre);
        txtNombre.setBounds(140, 110, 280, 30);

        txtNumero.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(txtNumero);
        txtNumero.setBounds(140, 160, 280, 30);

        btnGuardar.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(450, 110, 250, 27);

        btnEditar.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        btnEditar.setText("Modificar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar);
        btnEditar.setBounds(40, 450, 200, 27);

        btParrilla.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        btParrilla.setText("Modificar Parrilla");
        btParrilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btParrillaActionPerformed(evt);
            }
        });
        getContentPane().add(btParrilla);
        btParrilla.setBounds(500, 450, 200, 27);

        btnLimpiar.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(450, 160, 250, 27);

        btnSalir.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(500, 520, 200, 27);

        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProductos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 210, 660, 220);

        btnBorrar1.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        btnBorrar1.setText("Borrar");
        btnBorrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar1);
        btnBorrar1.setBounds(270, 450, 200, 27);

        jLabel4.setText("________________________________________________________________________________________________________________________________");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-20, 60, 768, 30);

        jLabel5.setText("________________________________________________________________________________________________________________________________");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-10, 0, 768, 30);

        setSize(new java.awt.Dimension(749, 609));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btParrillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btParrillaActionPerformed
        this.vnParrilla();
    }//GEN-LAST:event_btParrillaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        this.adicionarCanal();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.vnInicio();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
        // TODO add your handling code here:
        this.seleccionarCanal();
    }//GEN-LAST:event_tablaProductosMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        this.limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBorrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrar1ActionPerformed
        // TODO add your handling code here:
        this.borrarCanal();
    }//GEN-LAST:event_btnBorrar1ActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        this.editarCanal();
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    
    private void cargarDatos() {

        ArrayList<Canal> lista = miCanal.getCanal();
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Id");
        modelo.addColumn("Nombre");
        modelo.addColumn("Numero");

        for (Canal producto : lista) {

            Object[] datos = {
                producto.getId(),
                producto.getNombreCanal(),
                producto.getNumeroCanal()
            };
            modelo.addRow(datos);

        }
        this.tablaProductos.setModel(modelo);
        interactionButtonParrilla();
    }

    private void adicionarCanal() {
        if (txtNombre.getText().isEmpty() || txtNumero.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor! No dejar campos vacios");
        } else {
            String nombre = txtNombre.getText();
            String numero = txtNumero.getText();

            Canal p = new Canal();
            p.setNombreCanal(nombre);
            p.setNumeroCanal(numero);

            boolean r = miCanal.adicionarCanal(p);

            if (r) {
                JOptionPane.showMessageDialog(this, "Se almaceno el canal", "Atencion", JOptionPane.INFORMATION_MESSAGE);
                this.canalSeleccionado = null;
                cargarDatos();
                limpiar();

            } else {
                JOptionPane.showMessageDialog(this, "No se almaceno el canal, intentelo de nuevo", "Atencion", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void borrarCanal() {

        if (canalSeleccionado == null) {
            return;
        }

        boolean rta = miCanal.borrarCanal(canalSeleccionado);
        if (rta) {
            JOptionPane.showMessageDialog(this, "Se Borro el canal", "Atencion", JOptionPane.INFORMATION_MESSAGE);
            this.canalSeleccionado = null;
            cargarDatos();
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "No se Borro el canal, intentelo de nuevo", "Atencion", JOptionPane.ERROR_MESSAGE);
        }
    }
  
    private void editarCanal(){
        if(canalSeleccionado == null)
            return;
    
        String marca = txtNombre.getText();
        String modelo = txtNumero.getText();
        
        canalSeleccionado.setNombreCanal(marca);
        canalSeleccionado.setNumeroCanal(modelo);
        
        boolean rta = miCanal.editarProducto(canalSeleccionado);
        if(rta){
            JOptionPane.showMessageDialog(this, "Se modifico el canal","Atencion",JOptionPane.INFORMATION_MESSAGE);
            this.canalSeleccionado = null;
            cargarDatos();
            limpiar();
        }else{
            JOptionPane.showMessageDialog(this, "No se modifico el canal, intente de nuevo","Atencion",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void seleccionarCanal() {
        int fila = tablaProductos.getSelectedRow();
        Long identificacion = (Long) tablaProductos.getValueAt(fila, 0);
        canalSeleccionado = this.miCanal.buscarCanal(identificacion);
        this.txtNombre.setText(canalSeleccionado.getNombreCanal());
        this.txtNumero.setText(canalSeleccionado.getNumeroCanal());
        interactionButtonParrilla();
    }
    
    private void limpiar() {
        btnGuardar.setEnabled(true);
        btnEditar.setEnabled(true);
        this.txtNombre.setText("");
        this.txtNumero.setText("");
    }
    
    public void interactionButtonParrilla(){
        if (this.canalSeleccionado == null) {
            this.btParrilla.setEnabled(false);
        } else {
            this.btParrilla.setEnabled(true);
        }
    }
    
    public void vnParrilla(){
        VentanaParrilla p = new VentanaParrilla(this.canalSeleccionado);
        p.setVisible(true);
        this.setVisible(false);
    }
    
    public void vnInicio(){
        VentanaInicio c = new VentanaInicio();
        c.setVisible(true);
        this.setVisible(false);
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btParrilla;
    private javax.swing.JButton btnBorrar1;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
