package gui;
/**
 *
 * @author Carlos Z
 */
public class VentanaInicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */

    public VentanaInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTCanal = new javax.swing.JButton();
        BTSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        BTCanal.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        BTCanal.setText("Canales");
        BTCanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTCanalActionPerformed(evt);
            }
        });
        getContentPane().add(BTCanal);
        BTCanal.setBounds(40, 110, 323, 30);

        BTSalir.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        BTSalir.setText("Salir");
        BTSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BTSalir);
        BTSalir.setBounds(40, 170, 323, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("ProgramaT");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 40, 138, 28);

        jLabel2.setText("_______________________________________________________________________");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 10, 418, 14);

        jLabel3.setText("_______________________________________________________________________");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 70, 418, 14);

        setSize(new java.awt.Dimension(416, 268));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTCanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTCanalActionPerformed
        // TODO add your handling code here:
        this.vnCanales();
    }//GEN-LAST:event_BTCanalActionPerformed

    private void BTSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSalirActionPerformed
        // TODO add your handling code here:
        this.salir();
    }//GEN-LAST:event_BTSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTCanal;
    private javax.swing.JButton BTSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    public void vnCanales(){
        Ventana c = new Ventana();
        c.setVisible(true);
        this.setVisible(false);
    }
    public void salir(){
        dispose();
    }
}
